version: '3'

services:
    app:
        build: .
        image: bimbingan_pkl_app
        container_name: bimbingan_pkl_app
        restart: unless-stopped
        tty: true
        environment:
            SRVICE_NAME: app
        working_dir: /var/www/bimbingan_pkl_app
        volumes:
            - .:/var/www/bimbingan_pkl_app
            - .:/storage/php.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            -bimbingan_pkl_app
    webserver:
        image: nginx:alpine
        container_name: nginxbimbingan_pkl_app
        restart: unless-stopped
        tty: true
        ports:
            - "2022:80"
        volumes:
            - .:/var/www/bimbingan_pkl_app
            - ./storage/:/etc/nginx/conf.d/
        networks:
            -bimbingan_pkl_app

    db:
        image: mysql:5.7
        container_name: db_bimbinganpkl
        networks:
            - bimbingan_pkl_app
        restart: unless-stopped
        tty: true
        ports:
            - "20222:3306"
        volumes:
            - lbdata:/var/lib/mysql
        environment:
            MYSQL_PASSWORD: laraveldocker
            MYSQL_ROOT_PASSWORD: laraveldocker
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks:
            - bimbingan_pkl_app

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: pmalaraveldocker
        links:
            - db
        restart: always
        ports:
            - 7000:80
        networks:
            - bimbingan_pkl_app

#NETWORKS
networks:
    bimbingan_pkl_app:
        driver: bridge
#VOLUMES
volumes:
    lbdata:
    driver: local
